# Generated by Django 5.1.5 on 2025-01-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_online_alter_useravatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
