# Generated by Django 5.1.5 on 2025-01-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_useravatar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar_url',
            field=models.CharField(max_length=128),
        ),
    ]
