# Generated by Django 5.1.5 on 2025-01-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar_url',
            field=models.CharField(max_length=512),
        ),
    ]
